# Generated by Django 2.2.18 on 2021-02-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('deals', '0001_initial'), ('deals', '0002_auto_20210210_0649')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.PositiveIntegerField(verbose_name='Сумма сделки')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время регистрации сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item', verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
