# Generated by Django 2.2.18 on 2021-02-16 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20210210_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма сделки'),
        ),
    ]
