# Generated by Django 2.2.20 on 2021-04-26 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0003_auto_20210426_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='spent_money',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)],
                                    verbose_name='Сумма потраченных денег за весь период'),
        ),
    ]
