# Generated by Django 2.2.20 on 2021-04-26 13:03

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0005_auto_20210426_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='spent_money',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD',
                                                   max_digits=14,
                                                   verbose_name='Сумма потраченных денег за весь период'),
        ),
    ]
