# Generated by Django 2.2.18 on 2021-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара, шт')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость товара')),
            ],
        ),
    ]
