# Generated by Django 2.2.18 on 2021-02-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_squashed_0003_auto_20210210_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
